# Generated by Django 5.1.1 on 2024-10-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_author_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
